### ISSUE TITLE
about the mask of kitti dataset

### ISSUE THREAD

**Issue by yiying66** [feihuzhang/GANet#58]
Hi, thank you for your amazing work!
I find that you set the mask of disp map is `mask = target < opt.max_disp` when training, why didn't you set it be `(target>0)&(target<=opt.max_disp)` , I have trying to change it to  `(target>0)&(target<=opt.max_disp)` , but it makes my loss concussion and does not converge.

**Comment by feihuzhang** [comment]
This is because in the dataloader, the invalid locations/values of kitti data are all set to an extremely large value since for other datasets, zeros are valid disparity values.  

But you should not have the issue if you just revise this line. Maybe you need to check whether there is any other places you changed which caused this issue.

**Comment by yiying66** [comment]
Thank you for your reply! I found it is my mistake when preprocessing the dataset.

**Comment by udaykusupati** [comment]
Can you please let me know what your mistake was? My loss is stuck on kitti too.

**Comment by adita15** [comment]
what is the training_list and val_list In the arguments passed to the training function?
