### ISSUE TITLE
Does GANet produce floating point disparity?

### ISSUE THREAD

**Issue by jasjuang** [feihuzhang/GANet#61]
Hi, I read the GANet paper and it is clever on how you integrate SGM and DNN. My question is based on my understanding, SGM produces an 8-bit discrete disparity output, which is not ideal for some applications that require more than 256 kinds of depth value. Methods like [PatchMatch](http://www.bmva.org/bmvc/2011/proceedings/paper14/paper14.pdf) is able to produce a 32-bit continuous floating-point disparity output. Based on the output in the [illustration folder](https://github.com/feihuzhang/GANet/tree/master/illustration), GANet seems to only produce 8-bit discrete disparity output as well. Is that correct?

**Comment by feihuzhang** [comment]
All the state-of-the-art end-to-end stereo matching networks produce float accuracy. This is because they all use regression loss or display regression for training and disparity prediction. Not the old winner-take-all strategy as the traditional methods.
SGA is only for cost aggregation, it has no relationship with the foat or int accuracy.
